apiVersion: apps/v1
kind: Deployment
metadata:
  name: temperaturas-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temperaturas-backend
  template:
    metadata:
      labels:
        app: temperaturas-backend
    spec:
      containers:
      - name: temperaturas-backend
        image: nallepuz/temperaturas-backend:v1
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: temperaturas-backend
spec:
  selector:
    app: temperaturas-backend
  ports:
  - port: 5000
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temperaturas-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temperaturas-frontend
  template:
    metadata:
      labels:
        app: temperaturas-frontend
    spec:
      containers:
      - name: temperaturas-frontend
        image: nallepuz/temperaturas-frontend:v1
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: temperaturas-frontend
spec:
  type: LoadBalancer
  selector:
    app: temperaturas-frontend
  ports:
  - port: 80
    targetPort: 3001